# Generated by Django 6.0.3 on 2026-04-29 08:48

import ledger.models
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('sno', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('sno_sequence', models.PositiveIntegerField(default=0)),
                ('ano', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('ano_sequence', models.PositiveIntegerField(default=0)),
                ('full_name', models.CharField(max_length=150)),
                ('father_or_husband_name', models.CharField(blank=True, default='', max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.TextField(blank=True, default='')),
                ('occupation', models.CharField(blank=True, default='', max_length=120)),
                ('identity_proof_type', models.CharField(blank=True, default='', max_length=50)),
                ('identity_proof_name', models.CharField(blank=True, default='', max_length=150)),
                ('identity_proof_number', models.CharField(blank=True, default='', max_length=50)),
                ('identity_proof_file', models.FileField(blank=True, null=True, upload_to='customers/identity/')),
                ('address_proof_type', models.CharField(blank=True, default='', max_length=50)),
                ('address_proof_file', models.FileField(blank=True, null=True, upload_to='customers/address/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='customers/photos/')),
                ('item_type', models.CharField(blank=True, default='', max_length=50)),
                ('metal_type', models.CharField(blank=True, default='', max_length=50)),
                ('purity_or_karat', models.CharField(blank=True, default='', max_length=30)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('number_of_stones', models.PositiveIntegerField(blank=True, null=True)),
                ('gemstone_type', models.CharField(blank=True, default='', max_length=60)),
                ('gemstone_carat_or_quantity', models.CharField(blank=True, default='', max_length=60)),
                ('hallmark_or_makers_mark', models.CharField(blank=True, default='', max_length=120)),
                ('remarks', models.TextField(blank=True, default='')),
                ('item_condition', models.CharField(blank=True, default='', max_length=50)),
                ('jewelry_photo', models.FileField(blank=True, null=True, upload_to='customers/jewelry/')),
                ('jewel_entries', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('sno_format', models.CharField(default='SNO-{number:04}', max_length=80, validators=[ledger.models.validate_sequence_format])),
                ('ano_format', models.CharField(default='ANO-{number:04}', max_length=80, validators=[ledger.models.validate_sequence_format])),
                ('next_sno_number', models.PositiveIntegerField(default=1)),
                ('next_ano_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
